### PR TITLE
fix(dialog): missing flyAndScale

### PR DESCRIPTION
**Pull request by sunsreng**
export flyAndScale from internal to allow dialog to use it.

### CODE REVIEW

**Comment by huntabyte** [comment]
Rather than exporting everything from our `internal/styles`, we should just include the function itself in the preview code snippet if peeps want to use the same transition effect.

Anything inside `internal` should be capable of being changed without needing to semver the package, as those APIs shouldn't be exposed to the users of the package.

**Review by huntabyte — CHANGES_REQUESTED** [review]
We should copy the function from internal over to the preview snippet rather than exporting from internal.

**Comment by sunsreng** [comment]
We should place animation to be able use, as it's also required to use.
ex: in the dialog example.

**Comment by TGlide** [comment]
> @sunsreng Why was this closed?

Per @huntabyte's reply:

> Rather than exporting everything from our internal/styles, we should just include the function itself in the preview code snippet if peeps want to use the same transition effect.

> Anything inside internal should be capable of being changed without needing to semver the package, as those APIs shouldn't be exposed to the users of the package.

**Comment by voxpelli** [comment]
@TGlide Yes, but that was never done?

> include the function itself in the preview code snippet if peeps want to use the same transition effect

Should I open an issue to track that then?

**Comment by TGlide** [comment]
> @TGlide Yes, but that was never done?
> 
> > include the function itself in the preview code snippet if peeps want to use the same transition effect
> 
> Should I open an issue to track that then?

Feel free!

**Pull request closed without merging**
