### PR TITLE
fix(link preview, menu): interact outside transition out bug during unmounting

### PR DESCRIPTION
**Pull request by anatolzak**
closes https://github.com/melt-ui/melt-ui/issues/1039

This was previously fixed in https://github.com/melt-ui/melt-ui/pull/1006 using `sleep(0)`, however this seems to have been removed during a refactor since then in the link preview and menu builders.

### Menu Before

https://github.com/melt-ui/melt-ui/assets/53095479/c2ab7048-de15-472a-a629-680ce5aedb1a

### Menu After

https://github.com/melt-ui/melt-ui/assets/53095479/9b8060a8-de7f-418a-a65e-381558fc4651

### Link Preview Before

https://github.com/melt-ui/melt-ui/assets/53095479/e2f3e666-5da6-4571-81b1-316a4695d3fc

### Link Preview After

https://github.com/melt-ui/melt-ui/assets/53095479/b60ff3b5-2708-422e-8bfb-2c8382735165

### Tooltip 🚫

https://github.com/melt-ui/melt-ui/assets/53095479/d5618e43-f92f-4f0d-8f63-7ac0ee2055a2

With the tooltip, I am not sure what to do. It takes `sleep(100)`  in the tooltip content blur handler to prevent this issue consistently (with less than 40ms, the issue happens from time to time). Let me know what you think about this...

### CODE REVIEW

**Comment by TGlide** [comment]
@anatolzak thank you!

Let's fix the tooltip, but create a **TODO** or issue to investigate why this happens.

**Comment by anatolzak** [comment]
@TGlide great! I added the temp fix for the tooltip. So this is ready to be merged now

**Comment by anatolzak** [comment]
@TGlide the tooltip is driving me crazy. Now 40 is not enough either. Such a weird bug. I will add 100ms for now, which seems to work.

**Comment by TGlide** [comment]
> @TGlide the tooltip is driving me crazy. Now 40 is not enough either. Such a weird bug. I will add 100ms for now, which seems to work.

100ms is quite a lot 🤔 Let's leave it as it was then and create an issue for it

**Comment by TGlide** [comment]
> @TGlide just making sure, do you mean to change it to 40ms or 0ms?

0ms

**Comment by anatolzak** [comment]
@TGlide ok, done!

**Comment by anatolzak** [comment]
@TGlide I finally figured out the root issue for this and solved it in the following PR https://github.com/melt-ui/melt-ui/pull/1059

This fixes the issue with the tooltip as well without introducing any delays.

Closing this PR in favor of https://github.com/melt-ui/melt-ui/pull/1059

**Pull request closed without merging**
