### PR TITLE
Added code example to override closeDelay for individual toast (see #554)

### PR DESCRIPTION
**Pull request by lolcabanon**
Very simple. Added code example in the doc to show how to override default values of the toaster for individual toasts.

Feel free to point me if there would be some other place that would benefit this info!

### CODE REVIEW

**Comment by geerew** [comment]
Is there a better way to show the parameters of the helper function? 

Examples are great but it needs drawn out in the schema too..

**Review by TGlide — COMMENTED** [review]
Thank you for the PR! I think it'd be best to add a sub-section under usage detailing this behaviour instead.

**Comment by lolcabanon** [comment]
Hey!

@TGlide ! I just updated the doc with a new section. Tell me what you think of it!

@geerew I agree it should be in the schema... But I am not sure how to do it! If you can give me an example or template, that would be great. Would you just add it to the description?

I guess you are referring to this part in the doc?

```md
<!-- melt-ui/src/docs/content/builders/toast.md -->

## API Reference

<APIReference {schemas} />
```
```ts
// melt-ui/src/docs/data/builders/toast.ts

const builder = builderSchema(BUILDER_NAME, {
        // ...
	helpers: [
		{
			name: 'addToast',
			type: '(props: AddToastProps<T>) => void',
			description: 'A helper function to add a toast to the toasts store.',
		},
                // ...
	],
        // ...
});
```

Thank you both for the follow-up! :sun_with_face:

**Comment by TGlide** [comment]
> I agree it should be in the schema... But I am not sure how to do it! If you can give me an example or template, that would be great. Would you just add it to the description?

This is a docs issue currently. We can include longer schemas, but it's quite cumbersome currently. In a future iteration the API reference should be auto-generated, where it won't be a problem, but for now this is sufficient.

**Review by TGlide — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
