### PR TITLE
test: focus trap deactivates on escape if closeOnEscape: false

### PR DESCRIPTION
**Pull request by anatolzak**

### CODE REVIEW

**Review by huntabyte — APPROVED** [review]
You're awesome!

**Comment by huntabyte** [comment]
Are these the same tests added to #1094 ?

**Comment by anatolzak** [comment]
@huntabyte no, this tests pressing escape. the other tests clicking outside

**Comment by huntabyte** [comment]
> @huntabyte no, this tests pressing escape. the other tests clicking outside

Sorry I forgot how to read for a second there 😃

**Comment by anatolzak** [comment]
@huntabyte no hard feeling :)

**Pull request merged**
