### PR TITLE
feat(tags-input): split on paste

### PR DESCRIPTION
**Pull request by fernandolguevara**
related to #1227

tags-input-split-on-paste

### CODE REVIEW

**Review by dfralan — APPROVED** [review]

**Comment by Wizzel1** [comment]
@fernandolguevara can this please be merged?

**Comment by fernandolguevara** [comment]
@TGlide, what do you think about this?

**Review by dfralan — APPROVED** [review]

**Comment by dfralan** [comment]
BIS

**Review by TGlide — COMMENTED** [review]
Awesome, thank you!

**Review by TGlide — APPROVED** [review]
Awesome, thank you!

**Comment by Wizzel1** [comment]
Has this been reverted? Doesn't work with bits-ui `0.21.13`

**Pull request merged**
