### PR TITLE
change/pin-deletion

### PR DESCRIPTION
**Pull request by wesharper**
This is a draft that changes the functionality of the pin-input builder to address issue #319. 

I still need to update tests and stories, but want feedback on whether this is a desirable change before doing that work.

### CODE REVIEW

**Comment by TGlide** [comment]
This is awesome! One thing though, hitting backspace shouldn't immediately go back. Instead, it should only delete the current item, and keep the focus there. If you enter backspace on an empty item, it should move the focus back **and** delete the item on the newly focused input

**Comment by wesharper** [comment]
@TGlide what you're describing is how the builder already works. I did this in response to feature request #319, which requests different behavior based on other pin inputs in the wild.

**Comment by TGlide** [comment]
> @TGlide what you're describing is how the builder already works. I did this in response to feature request #319, which requests different behavior based on other pin inputs in the wild such as Amazon and PayPal. I essentially want your blessing to change the default behavior altogether.

It is not how it currently works. Currently, pressing backspace on an input without value just moves the focus to the previous input, but keeps the previous input value intact. It should delete it as well. 

Compare the current behaviour with https://zagjs.com/components/react/pin-input

**Comment by cd-slash** [comment]
I wonder if it's easier to give an example - if I type `1` `2` `4` `backspace` `3` I should have the first 3 input boxes populated with `123` and the next keystroke should either populate the next box, or if a `backspace` then the 3 would be removed.

This is different from the current behavior where typing  `1` `2` `4` `backspace` `3` would leave the pin populated with `1243` because the current behavior is to simply let the backspace move the focus back to the previous input element.

Perhaps quantifying / testing the PR in terms of what the anticipated outcome is will allow us to describe the intended / desired behavior?

**Comment by TGlide** [comment]
Closed in favor of https://github.com/melt-ui/melt-ui/commit/adcf8853c7840f3dc2367723efe22132d7633214

Thank you for the PR though 🙏

**Comment by TGlide** [comment]
Closed in favor of https://github.com/melt-ui/melt-ui/commit/adcf8853c7840f3dc2367723efe22132d7633214

Thank you for the PR though 🙏

**Comment by wesharper** [comment]
No worries, @TGlide sorry I couldn't get to it. Busy few days at work. Thanks for merging this!

**Pull request closed without merging**
