### PR TITLE
New Builder: Spin Button

### PR DESCRIPTION
**Pull request by abdel-17**
This PR adds a new **Stepper**  builder, also known elsewhere as Spinbutton.

https://github.com/melt-ui/melt-ui/assets/88583085/3cdc9c44-6f94-4881-8d44-bbb849496f5c

Follows the [APG Spinbutton Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/#:~:text=A%20spinbutton%20is%20an%20input,the%20minute%20of%20an%20hour.)

## Minor Caveats
When VoiceOver announces a stepper, it suggesting controlling it by pressing Control-Option-Up/Down, but this functionality only works with the native `<input type="number">`.

voiceover-bug

For some reason, I wasn't able to listen to the Option and Up/Down keydown events to manually get around it. Only the Control key emits a `keydown` event when VoiceOver is active and the stepper is in focus. We should at least mention this issue in the docs.

Related issue: https://github.com/microsoft/fluentui/issues/13606

### CODE REVIEW

**Comment by abdel-17** [comment]
So, there's a small bug with `loop` and `step`.

Consider the case where `step: 2` and `loop: true`. If `value` is currently `max` and I increment it, it should be `min + 1`, but with the current implementation, it's `min`. Trying to fix this now.

**Comment by huntabyte** [comment]
Are we sure we want to call this a Stepper? I know that's what it's announced as to screen readers, but when I see "Stepper" as a component I think of something like this: https://www.skeleton.dev/components/steppers

**Comment by abdel-17** [comment]
Prior to researching implementations, I had never heard the term "spinbutton". Maybe it's because English is not my first language, but "stepper" to me sounds more intuitive. If you google stepper input, it shows what you would call a "spinbutton" rather than Skeleton's stepper. Maybe we can call it StepperInput?

image

**Comment by huntabyte** [comment]
Yeah when you put "input" alongside it, it makes more sense. I'll defer to @TGlide on this one b/c I believe he wanted to call it a SpinButton originally

**Comment by TGlide** [comment]
Let's call it `spinbutton`. Both the APG pattern and the aria role is called like so, and as @huntabyte said, Stepper may be confusing.

**Comment by abdel-17** [comment]
Yeah sure

**Comment by huntabyte** [comment]
Reminder to myself to look into the VO issues for this one

**Comment by huntabyte** [comment]
Hey @TGlide, once you give the implementation a review/approval I'll add in unit tests for this. Just don't want to have to change a bunch of tests if you propose an architectural change!

**Comment by TGlide** [comment]
Closing, lets add this with Runes

**Pull request closed without merging**
