### PR TITLE
[Accordion] Finish adding aria attributes & add example previews

### PR DESCRIPTION
**Pull request by huntabyte**
This PR adds the missing `aria-controls` attribute to the accordion item trigger and adds previews that showcase a `multiple` accordion, as well as an accordion with a `disabled` item. I've also added a callout to the docs that mention the importance of wrapping the trigger in either a heading element or an element with the `role="heading"` and the `aria-level` attributes to ensure their components are accessible.

### CODE REVIEW

**Comment by TGlide** [comment]
Should we maybe create a `heading` store, similar to radix? Or is it overkill?

**Comment by huntabyte** [comment]
I guess my concern with that would be what we default the heading level to be, or if we'd just want to make that be a required argument to the call.

So something like:

```svelte
<anything melt={$heading('3')} />
```

**Comment by TGlide** [comment]
> I guess my concern with that would be what we default the heading level to be, or if we'd just want to make that a required argument to the call.
> 
> So something like:
> 
> ```svelte
> <anything melt={$heading('3')} />
> ```
> 
> Let me know if you think this might be a better approach and I'll make the change and update the docs to document it!

Required argument, I'd say!

**Comment by huntabyte** [comment]
You got it! @TGlide , coming right up!

**Pull request merged**
