### PR TITLE
[Table of Contents] fix smooth scroll and scroll offset

### PR DESCRIPTION
**Pull request by MadeBaruna**
Setting location hash will trigger browser navigation jump

### CODE REVIEW

**Comment by TGlide** [comment]
What issue does this solve?

**Comment by MadeBaruna** [comment]
On the table of content, if you click the link, it will jump directly to the heading, ignoring the smooth scroll and the scroll offset

**Comment by TGlide** [comment]
This brings a regression, as even when setting scroll-behavior to auto, the scroll is now smooth.

**Comment by TGlide** [comment]
Thank you! 🎉

**Pull request merged**
