### PR TITLE
Fix: Generic Type Defaults

### LINKED ISSUE #907: `Select` doesn't allow `true` to be set for `multiple` prop
### Describe the bug

We are updating our custom `Select` component to work with single and multiple selections.

When trying to provide `true` as default value for `multiple`, we encounter the following TS issue:

Screenshot from 2024-01-12 10-55-06

`CreateSelectProps['multiple']` should allow `boolean | undefined` instead of `false | undefined`

### Reproduction

N/A

### Logs

_No response_

### System Info

```bash
N/A
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by abdel-17**
Fixes #907

### CODE REVIEW

**Comment by huntabyte** [comment]
CleanShot 2024-02-16 at 15 26 24@2x

This change now requires an explicit `true` in the type argument as well as in the form of a `multiple` prop.

**Comment by abdel-17** [comment]
This problem exists in the "develop" branch as well. It happens when you specify the generic type. It doesn't infer them from the props anymore, so you must pass a generic explicitly.

Screenshot 2024-02-16 at 10 34 05 PM

**Comment by abdel-17** [comment]
I agree that discriminated unions are much nicer. I'll explore that solution.

**Comment by huntabyte** [comment]
@abdel-17 I see, I didn't notice that introduced the requirement of the multiple generic as well. I still stand by my comment of it being a regression in terms of DX vs just requiring the `type` prop to discriminate, which is more intuitive than having to figure out that on top of specifying `multiple: true` you also have to now pass in your type _and_ the fact that its multiple in the form of a generic. It's a bit bass ackwards.



```ts
const stuff = createSelect<string, true>({
	multiple: true;
})
```

vs

```ts
const stuff = createSelect<string>({
	type: 'multiple'
})
```

**Comment by huntabyte** [comment]
> I agree that discriminated unions are much nicer. I'll explore that solution.

I know when I discussed this with @TGlide in the past he was uneasy about the idea of requiring the `type` prop but maybe his mind has changed now that all these issues around types keep popping up 😂

**Comment by abdel-17** [comment]
> > I agree that discriminated unions are much nicer. I'll explore that solution.
> 
> I know when I discussed this with @TGlide in the past he was uneasy about the idea of requiring the `type` prop but maybe his mind has changed now that all these issues around types keep popping up 😂

You can definitely do discriminated unions without requiring the type prop! I'll commit changes in a moment.

**Comment by huntabyte** [comment]
> > > I agree that discriminated unions are much nicer. I'll explore that solution.
> > 
> > 
> > I know when I discussed this with @TGlide in the past he was uneasy about the idea of requiring the `type` prop but maybe his mind has changed now that all these issues around types keep popping up 😂
> 
> You can definitely do discriminated unions without requiring the type prop! I'll commit changes in a moment.

Discriminated unions without a discriminator... I'm interested to see this one 👨‍🍳

**Comment by abdel-17** [comment]
@huntabyte The basic idea is to make the discriminator optional in the "single" case and required in the "multiple" case.
```ts
type SingleAccordionProps = {
	multiple?: false;
	defaultValue?: string;
};

type MultipleAccordionProps = {
	multiple: true;
	defaultValue?: string[];
};

export type CreateAccordionProps = SingleAccordionProps | MultipleAccordionProps;

// Doesn't error
const _1: CreateAccordionProps = {
	defaultValue: 'a',
};

// Doesn't error
const _2: CreateAccordionProps = {
	multiple: false,
	defaultValue: 'a',
};

// Errors
const _3: CreateAccordionProps = {
	defaultValue: ['a'],
};

// Doesn't error
const _4: CreateAccordionProps = {
	multiple: true,
	defaultValue: ['a'],
};
```

I'm facing some issues with type inference in the builder function itself, but I'll work my way through it.

**Comment by TGlide** [comment]
Closing because of internal discussions on Discord. A select overhaul is coming soon

**Pull request closed without merging**
