### PR TITLE
[New Builder] Navigation Menu

### PR DESCRIPTION
**Pull request by huntabyte**
Work in progress

### CODE REVIEW

**Comment by buhodev** [comment]
What's the status of this PR? Is there something I can do to help? 😄

**Comment by huntabyte** [comment]
> What's the status of this PR? Is there something I can do to help? 😄

The status is biting a bit more off than I can chew at once! You're more than welcome to take it over if you have the cycles at the moment!

**Comment by buhodev** [comment]
Sure! Just to have a clearer picture, what's blocking merging this right now?

**Comment by gleerman** [comment]
@huntabyte I'm looking to contribute to this project and this seems like a nice feature I could try to pick up. Would you mind rebasing this branch onto `develop` first?

**Comment by PixeledCode** [comment]
Hi, @huntabyte any status on this? Can I pick it up?

**Comment by JohnnyJTH** [comment]
Why did you close this?

**Comment by TGlide** [comment]
> Why did you close this?

It is quite outdated with how we currently create builders, and all context of creation has been lost as it's quite the old PR. Best for ot to be revisited entirely

**Comment by JohnnyJTH** [comment]
> > Why did you close this?
> 
> It is quite outdated with how we currently create builders, and all context of creation has been lost as it's quite the old PR. Best for it to be revisited entirely 

That's fair, hope the navigation menu won't be forgotten.

**Pull request closed without merging**
