### PR TITLE
fix(dialog,popover):focus trap `closeOnOutsideClick: false` bug

### PR DESCRIPTION
**Pull request by anatolzak**
closes https://github.com/melt-ui/melt-ui/issues/1084

Focus trap should not deactivate on click outside if the prop `closeOnOutsideClick: false` is passed. To make sure that this issue https://github.com/melt-ui/melt-ui/issues/452 doesn't occur, we need to allow outside clicks in the focus trap--this doesn't affect the content getting closes.

### Popover Before with `closeOnOutsideClick: false`

https://github.com/melt-ui/melt-ui/assets/53095479/f4e9d207-dc24-455a-93ed-1c0cee4baa9f

### Popover After

https://github.com/melt-ui/melt-ui/assets/53095479/3bc5c44d-9810-484b-8456-792eb9754fa5

### Dialog Before with `closeOnOutsideClick: false`

https://github.com/melt-ui/melt-ui/assets/53095479/55c63c71-d823-4d4f-bc7f-6ea719cf412b

### Dialog After

https://github.com/melt-ui/melt-ui/assets/53095479/d85f6682-aa51-4efb-a1c6-40b831e96471

### CODE REVIEW

**Comment by TGlide** [comment]
Merge conflicts :)

**Comment by anatolzak** [comment]
just did @TGlide  :)

**Comment by huntabyte** [comment]
Do you think you could add a regression test? One that fails without the changes in this PR but passes with it.

**Comment by anatolzak** [comment]
@huntabyte I tried to do it and gave up lol but I will get it done!

**Comment by huntabyte** [comment]
> @huntabyte I tried to do it and gave up lol but I will get it done!

Ah yeah focus states can be a bit of a PITA - have to slap a bunch of `sleep`s and/or `waitFor`s in there but don't beat yourself up about it if you already gave it a fair shot. I can verify from the videos, it just seems like something easy to regress on without a test.

**Comment by anatolzak** [comment]
@huntabyte added the tests!

**Review by huntabyte — APPROVED** [review]
💯

**Pull request merged**
