### PR TITLE
fix: various bug slider

### PR DESCRIPTION
**Pull request by paoloricciuti**
This fixes basically every bug in #323 and add the ability to specify min = 0, max = 1, step = .1 (it was not possible before)

I've also added some helpers to better manage floating point add, sub, mul and div (given that numbers can be floating point in the slider).

I'm making this a draft since i want to addresso some other thing before merging

- [x] try to add tests
- [x] address setting the values from the store not adhere to the step (we decided to forgo this because it might be an unpleasant user experience)
- [x] check if we want the sliders to stop when they meet (even if set via store)...i was discussing this with @TGlide 
- [x] verify that everything is correct (it's 1 am and i'm tired, i might have messed something up)

Sorry for the weird git history

### CODE REVIEW

**Comment by TGlide** [comment]
@paoloricciuti Oh I think we definitely want them to stop when we meet. The problem is, when they meet, and we stop dragging it, when we start dragging again, it only allows going towards one direction, which is not ideal. 

It should allow going to both, and then whichever direction you choose, is the one it should stick with until you stop dragging it again. Maybe this isn't possible though

Current behaviour:
https://github.com/melt-ui/melt-ui/assets/26071571/1cd7d9ff-b1d4-4a7e-a5a3-0b848474ac9c

**Comment by paoloricciuti** [comment]
> 

The range slider component from material UI doesn't stop for example and just start dragging the other handle which to be fair seems like a reasonable thing to do (unless the user literally want's a range of 0)...maybe we should go this route too?

**Comment by paoloricciuti** [comment]
https://github.com/melt-ui/melt-ui/assets/26281609/bebc1195-54c6-44d9-bdce-88da1ff1c587

I got this for the moment...it still has some quirk, like the fact that you can never have two range perfectly one over the other and the fact that depending on how fast you move you can leave your thumb way before but...does this kinda work for you guys?

**Comment by TGlide** [comment]
@paoloricciuti 

This is quite good to be honest! I do think we should allow having one thumb perfectly over the other though. 

A nitpick, which is not crucial but would be nice: In your example, if you have a thumb at 10, the other at 20, and drag the left thumb quickly over the other thumb to go to 30, I would expect the thumbs to be 20-30. This doesn't seem to be the case. As I said, this is not super important, but would be ideal

**Comment by paoloricciuti** [comment]
> @paoloricciuti
> 
> This is quite good to be honest! I do think we should allow having one thumb perfectly over the other though.
> 
> A nitpick, which is not crucial but would be nice: In your example, if you have a thumb at 10, the other at 20, and drag the left thumb quickly over the other thumb to go to 30, I would expect the thumbs to be 20-30. This doesn't seem to be the case. As I said, this is not super important, but would be ideal

Yeah i was trying to get the same effect too...the problem with this is that basicallly on pointermove it tries to get the actual closest thumb and swap to that. However when you move fast enaugh the mouse will "skip some bit"...i'll try to make it work however

**Comment by paoloricciuti** [comment]
> @paoloricciuti
> 
> This is quite good to be honest! I do think we should allow having one thumb perfectly over the other though.
> 
> A nitpick, which is not crucial but would be nice: In your example, if you have a thumb at 10, the other at 20, and drag the left thumb quickly over the other thumb to go to 30, I would expect the thumbs to be 20-30. This doesn't seem to be the case. As I said, this is not super important, but would be ideal

Update, i got this working

**Review by TGlide — APPROVED** [review]
Flawless, thank you so much! 🎉

**Pull request merged**
