### PR TITLE
fix(menu): focus on the trigger when rootActiveTrigger is defined

### LINKED ISSUE #867: 🐛Bug: Dropdown Menu - Focus on trigger button after page load
**Describe the bug**
Immediately after the page loads, it automatically focuses on the element that opens and closes the Dropdown menu.

**To Reproduce**
1. Go to https://melt-ui.com/docs/builders/dropdown-menu

**Expected behavior**
It should not be in focus immediately after the page loads

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Sonoma 14.2.1]
 - Browser [chrome]
 - Version [120.0.6099.129]

**Smartphone (please complete the following information):**

**Additional context**

To reproduce using SvelteLab, use the [Melt UI template](https://www.sveltelab.dev/?t=melt_ui) and modify the `src/routes/+page.svelte` file.

### PR DESCRIPTION
**Pull request by azukiazusa1**
fix #867.

When the page is first loaded, there is no need to focus on the trigger even if $rootOpen is false.

However, when rootActiveTrigger is set at the time it is mounted, the effect will be executed and the trigger will be focused.

Since we only need to pay attention to whether the menu is closed or not, we did not need to monitor the rootActiveTrigger.

### CODE REVIEW

**Comment by huntabyte** [comment]
> Since we only need to pay attention to whether the menu is closed or not, we did not need to monitor the rootActiveTrigger.

This isn't true if using `forceVisible` and conditionally rendering the menu, as you can see from the test I just added that is failing.

Instead, I think we should use a `closeMenu` function which would handle the focus restoration once the menu has closed, rather than focus being handled within the `effect`.

**Comment by huntabyte** [comment]
Let me confirm that this won't impact the auto refocus of the trigger when a user closes the menu using the keyboard. I added a test which is currently failing for it. There's probably a better way to handle the focus restoration rather than simply reacting to the `open`. Will do some explorations cause always focusing the button is def not the intended behavior.

**Review by huntabyte — APPROVED** [review]
Thank you!

**Comment by azukiazusa1** [comment]
Thanks for the review!

**Pull request merged**
