### PR TITLE
Resolves #687 Add skip to content button

### LINKED ISSUE #687: 📁Docs: Add 'Skip to Main Content' Button

### PR DESCRIPTION
**Pull request by evelinabe**
Skip to content button added. It does not work so well on the first page - it is the first item in the navigation order, but the focus is set to the popover button. Let me know what you think, and if there's something in the code that needs updating.

Resolves issue [#687](https://github.com/melt-ui/melt-ui/issues/687)

### CODE REVIEW

**Comment by TGlide** [comment]
Hey, thank you for the PR!

It seems the button isn't visible when focusing it. I can see in the console that it is focused, but nonetheless there is no visual indication. At least in the cloudflare preview!

**Comment by evelinabe** [comment]
> It seems the button isn't visible when focusing it. I can see in the console that it is focused, but nonetheless there is no visual indication. At least in the cloudflare preview!

I noticed that, too, took a look at the preview. It needed a higher z-index, I already pushed that change :)

**Comment by TGlide** [comment]
Hmm, the new preview still fails. I don't think z-1000 is a valid tailwind class, you may need to do `z-[1000]`

**Comment by evelinabe** [comment]
Strange, it works on my machine 🤔 
Giving it another go 🤞

**Comment by TGlide** [comment]
Awesome, it works now! Thank you so much for the contribution, and for putting up with the back and forth 😄

**Comment by evelinabe** [comment]
No problem, happy to help!

**Pull request merged**
